/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,jsx}'],
  theme: {
    extend: {
      colors: {
        'on-secondary-fixed-variant': '#574500',
        error: '#ba1a1a',
        'on-primary-fixed-variant': '#872020',
        'on-tertiary-container': '#bcbab4',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#474743',
        primary: '#6b090f',
        'surface-container-high': '#f9e3e1',
        'aligarh-red': '#8B2323',
        'inverse-surface': '#3a2d2c',
        background: '#fff8f7',
        'surface-container-highest': '#f3dedb',
        'surface-container-low': '#fff0ef',
        'secondary-container': '#fed65b',
        'on-primary-container': '#ffa099',
        outline: '#8b716f',
        'on-surface': '#241918',
        'primary-container': '#8b2323',
        'on-background': '#241918',
        'surface-dim': '#ebd5d3',
        secondary: '#735c00',
        'primary-fixed-dim': '#ffb3ad',
        'heritage-cream': '#F9F6F0',
        tertiary: '#343430',
        'on-tertiary': '#ffffff',
        'on-secondary-fixed': '#241a00',
        'surface-bright': '#fff8f7',
        'tertiary-fixed': '#e5e2dc',
        'error-container': '#ffdad6',
        'on-secondary-container': '#745c00',
        'on-secondary': '#ffffff',
        'ink-black': '#1A1A1A',
        'on-surface-variant': '#574140',
        'surface-container': '#ffe9e7',
        surface: '#fff8f7',
        'on-primary-fixed': '#410004',
        'tertiary-container': '#4b4a46',
        'on-primary': '#ffffff',
        'inverse-on-surface': '#ffedeb',
        'outline-variant': '#debfbd',
        'surface-tint': '#a73835',
        'on-tertiary-fixed': '#1c1c18',
        'inverse-primary': '#ffb3ad',
        'on-error-container': '#93000a',
        'stone-gray': '#545454',
        'surface-container-lowest': '#ffffff',
        'secondary-fixed-dim': '#e9c349',
        'primary-fixed': '#ffdad7',
        'tertiary-fixed-dim': '#c9c6c1',
        'surface-variant': '#f3dedb',
        'secondary-fixed': '#ffe088',
        'excellence-gold': '#D4AF37',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '24px',
        'stack-lg': '32px',
        'section-padding-mobile': '64px',
        'stack-sm': '8px',
        'section-padding-desktop': '120px',
        'container-max-width': '1280px',
        'stack-md': '16px',
      },
      maxWidth: {
        'container-max-width': '1280px',
      },
      fontFamily: {
        'headline-xl-mobile': ['EB Garamond', 'serif'],
        callquote: ['EB Garamond', 'serif'],
        'label-md': ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
        'body-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['EB Garamond', 'serif'],
        'headline-lg': ['EB Garamond', 'serif'],
        'headline-xl': ['EB Garamond', 'serif'],
        'headline-sm': ['EB Garamond', 'serif'],
        serif: ['EB Garamond', 'serif'],
        sans: ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'headline-xl-mobile': ['32px', { lineHeight: '40px', fontWeight: '600' }],
        callquote: ['24px', { lineHeight: '32px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-md': ['28px', { lineHeight: '36px', fontWeight: '500' }],
        'headline-lg': ['36px', { lineHeight: '44px', fontWeight: '500' }],
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-sm': ['22px', { lineHeight: '28px', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
